[package]
name = "rustpy"
version = "0.1.0"
authors = ["yuyu-hf <yuyuhf.ds@gmail.com>"]
edition = "2018"

[lib]
name = "rustpy"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
