name: rustpy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker-compose run work make build
    - name: lint
      run: docker-compose run work make lint
    - name: test
      run: docker-compose run work make test
